### ISSUE TITLE
URL API Compatibility

### ISSUE THREAD

**Issue by PabloSzx** [electerious/use-ackee#1]
The code used [here](https://github.com/electerious/use-ackee/blob/master/src/index.js#L33) is using the [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), which has bad compatibility with IE, Opera mini and old browsers, which is counterproductive in code which is intended to be used for tracking, including other stuff, the browser used.

https://caniuse.com/#feat=url

**Comment by electerious** [comment]
`use-ackee` has been made for React applications. It uses several new JS features that only work in old browsers when transpiled and polyfilled. Most React environments already do so. `ackee-tracker` (the default tracking script) works in most browsers and can be used without polyfills.
