### ISSUE TITLE
Access ackee instance

### ISSUE THREAD

**Issue by CookedApps** [electerious/use-ackee#4]
Hello, 

Is it possible to access the underlying acke-tracker instance in order to create actions? Or should I create a new one in addition to calling `useAckee()`?

**Comment by electerious** [comment]
Sorry for the late reply!

It's currently not possible to get the underlaying instance, but yes, you can create a new instance. Just make sure not to call `record`, because that's what `useAckee` does for you.

Adding actions support to `useAckee` would be cool BTW. A PR is welcome.

**Comment by b3nab** [comment]
Hi @electerious , do you accept a PR to add a simple return inside the hook to return the instance and be easily usable for everyone using react? :smile:
